### ISSUE TITLE
Validation incorrectly throws error on nil data

### ISSUE THREAD

**Issue by NullVoxPopuli** [beauby/jsonapi-deserializable#2]
```
{"data"=>nil}
The request MUST include a single resource object as primary data.
```

``` ruby
 JSONAPI::Deserializable::Resource.new('data' => nil)
JSONAPI::Parser::InvalidDocument: The request MUST include a single resource object as primary data.

# yet:
JSONAPI.parse_response!('data' => nil)
=> nil
```

**Comment by NullVoxPopuli** [comment]
so maybe this is a problem with https://github.com/beauby/jsonapi-validations

**Comment by beauby** [comment]
This is expected.

> [The request MUST include a single resource object as primary data.](http://jsonapi.org/format/#crud-creating)

**Comment by NullVoxPopuli** [comment]
Last I checked the schema,  the resource object was allowed to be nil

**Comment by beauby** [comment]
It is not (for a create/update payload). Could you point to the part of the spec you are referring to?
